version: '3.4'

services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  transport.mqtt1:
    image: ${DOCKER_REGISTRY-}transportmqtt1
    build:
      context: .
      dockerfile: src/Services/Transport/Transport.MQTT/Dockerfile

  transport.mqtt2:
    image: ${DOCKER_REGISTRY-}transportmqtt2
    build:
      context: .
      dockerfile: src/Services/Transport/Transport.MQTT/Dockerfile

  transport.mqtt1-dapr:
    image: "daprio/daprd:latest"

  transport.mqtt2-dapr:
    image: "daprio/daprd:latest"

  core.api:
    image: ${DOCKER_REGISTRY-}coreapi
    build:
      context: .
      dockerfile: src/Services/Core/Core.API/Dockerfile

  core.api-dapr:
    image: "daprio/daprd:latest"

  haproxy:
      image:  haproxy:latest