version: '3.4'


services:

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "15672:15672"

    expose:
        - "5672" 
    networks:
     - vangurdiot


  portainer:
    container_name: portainer
    restart: always
    ports:
      - "15000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker_volumes/portainer_data:/data
    networks:
     - vangurdiot


  ## application services

  transport.mqtt1:
    container_name: transport.mqtt1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NodeSettings__NodeName=MQTT_SERVER_1
    expose:
      - "1883"
      - "80"

    networks:
     - vangurdiot

  transport.mqtt1-dapr:
    container_name: transport.mqtt1-dapr
    command: [ "./daprd",
               "-app-id", "transport.mqtt1",
               "-app-port", "80",
               "-components-path", "/components"]
    depends_on:
      - transport.mqtt1
    network_mode: "service:transport.mqtt1"
    volumes:
    - ./dapr/components/:/components  


  transport.mqtt2:
    container_name: transport.mqtt2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NodeSettings__NodeName=MQTT_SERVER_2
    expose:
      - "1883"
      - "80"

    networks:
     - vangurdiot
 

  transport.mqtt2-dapr:
    container_name: transport.mqtt2-dapr
    command: [ "./daprd",
               "-app-id", "transport.mqtt2",
               "-app-port", "80",
               "-components-path", "/components"]
    depends_on:
      - transport.mqtt2
    network_mode: "service:transport.mqtt2"
    volumes:
    - ./dapr/components/:/components 

  core.api:
    container_name: core.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
       - "80" 
    networks:
     - vangurdiot

  core.api-dapr:
    container_name: core.api-dapr
    command: [ "./daprd",
               "-app-id", "core.api",
               "-app-port", "80",
               "-components-path", "/components"]
    depends_on:
      - core.api
    network_mode: "service:core.api"
    volumes:
    - ./dapr/components/:/components   

  haproxy:
      container_name: haproxy
      volumes:
       - ./docker_volumes/haproxy:/usr/local/etc/haproxy:ro
      links:
       - transport.mqtt1
       - transport.mqtt2
      ports:
       - "1883:1883"
       - "70:70"
      expose:
       - "1883"
       - "70"
      networks:
      - vangurdiot
  

networks:
 vangurdiot:

